#!/usr/bin/env python3
"""Deterministic code-metrics audit for Python projects — Python equivalent of
the .NET scripts/dotnet/metrics-audit.py (which runs Dependably.CodeMetrics
over Roslyn with the `.dependably` rules).

Rules (mirror the .NET gate; same rule names, same thresholds):
  cyclomatic   error  max 25    (radon cyclomatic complexity per function)
  mi           error  min 20    (radon Maintainability Index per module —
                                 module-level, which is how radon computes MI;
                                 per-function slices are unreliable)
  arguments    error  max 7     (positional+keyword params; long param lists)

Writes (same shape as the .NET versions, so the loop and queues behave the same):
  metrics-report.json   findings[] {ruleId, severity, location, message, remediation}
                        + functions[] (cc, args) + modules[] (MI, sloc)
  metrics-queue.md      worst offenders, worst-first by severity

Exit code: 0 = gate passed (no high findings), 1 = work remains.
--no-gate: scan and write reports but always exit 0.

Determinism: same source + same radon version => byte-identical report.
Pin the radon version (docs/code-quality-tools.md).

Requirements: `pip install radon`
"""
from __future__ import annotations

import argparse
import ast
import json
import os
import subprocess
import sys
from operator import itemgetter
from pathlib import Path


def git_root(start: Path) -> Path | None:
    try:
        return Path(
            subprocess.check_output(["git", "rev-parse", "--show-toplevel"], cwd=start, text=True, stderr=subprocess.DEVNULL).strip()
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


def git_root_or(first: Path, second: Path) -> Path | None:
    return git_root(first) or git_root(second)


def find_repo() -> Path:
    return git_root_or(Path.cwd(), Path(__file__).resolve().parent) or Path.cwd()


REPO = find_repo()
REPORT = REPO / "metrics-report.json"
QUEUE = REPO / "metrics-queue.md"

SKIPPED_DIRS = {".git", ".venv", "venv", "__pycache__", "node_modules",
                ".pytest_cache", "artifacts", "build", "dist", "site-packages"}

RULES = {
    "cyclomatic": {"severity": "high", "check": lambda cc: cc > 25,
                   "message": lambda cc: f"cyclomatic complexity {cc} exceeds max 25",
                   "remediation": "extract methods / introduce guard clauses or table-driven dispatch"},
    "mi": {"severity": "high", "check": lambda mi: mi < 20,
           "message": lambda mi: f"maintainability index {mi:.1f} below min 20",
           "remediation": "split the function, reduce nesting, add clarifying comments"},
    "arguments": {"severity": "moderate", "check": lambda n: n > 7,
                  "message": lambda n: f"{n} parameters exceed max 7",
                  "remediation": "bundle related parameters into a dataclass/config object"},
}


def kept_dirs(dirs: list[str]) -> list[str]:
    return list(filter(lambda d: d not in SKIPPED_DIRS, dirs))


def prune(dirs: list[str]) -> None:
    dirs[:] = kept_dirs(dirs)


def add_py_file(files: list[Path], root: str, name: str) -> None:
    if name.endswith(".py"):
        files.append(Path(root) / name)


def add_py_files(files: list[Path], root: str, names: list[str]) -> None:
    for name in names:
        add_py_file(files, root, name)


def iter_py_files() -> list[Path]:
    files: list[Path] = []
    for root, dirs, names in os.walk(REPO):
        prune(dirs)
        add_py_files(files, root, names)
    return files


def collect_args(counts: dict[int, int], child: ast.AST) -> None:
    if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
        counts[child.lineno] = arg_count(child.args)


def arg_count(args) -> int:
    all_args = args.posonlyargs + args.args + args.kwonlyargs
    return len(drop_self(all_args, args.args))


def drop_self(all_args: list, params) -> list:
    if method_params(params):
        return all_args[1:]
    return all_args


def method_params(params) -> bool:
    return bool(params) and params[0].arg in ("self", "cls")


def function_args(tree: ast.Module) -> dict[int, int]:
    """Map def-line -> positional+keyword arg count (excluding self/cls, *args, **kwargs)."""
    counts: dict[int, int] = {}
    for child in ast.walk(tree):
        collect_args(counts, child)
    return counts


def header_lines(report: dict) -> list[str]:
    s = report["summary"]
    return [
        "# Metrics queue (worst offenders, worst-first)",
        "",
        f"Generated by radon {report['generatorVersion']} over {s['scannedFiles']} files — "
        f"{s['functions']} functions in {s['modules']} modules",
        "",
        f"Findings: {s['findings']} total "
        f"({s['bySeverity']['high']} high / {s['bySeverity']['moderate']} moderate) — "
        f"high findings fail the gate",
        "",
        "## Findings (worst-first by severity)",
        "",
    ]


def finding_lines(findings: list[dict]) -> list[str]:
    lines: list[str] = []
    for f in findings:
        loc = f["location"]
        lines.append(f"- **{f['severity']}** `{f['ruleId']}` [{loc['file']}:{loc['line']}] {f['message']}")
        lines.append(f"  - Fix: {f['remediation']}")
    return lines


def module_lines(modules: list[dict]) -> list[str]:
    lines = ["", "## Lowest maintainability index (modules)", ""]
    for m in sorted(modules, key=itemgetter("mi"))[:15]:
        lines.append(f"- MI {m['mi']:>5.1f} | sloc {m['sloc']:>5} | {m['file']}")
    return lines


def function_lines(functions: list[dict]) -> list[str]:
    lines = ["", "## Highest cyclomatic complexity (functions)", ""]
    for m in sorted(functions, key=itemgetter("cyclomatic"), reverse=True)[:10]:
        lines.append(
            f"- cc {m['cyclomatic']:>3} | args {m['args']:>2} | "
            f"{m['fullname']} ({m['file']}:{m['line']})"
        )
    return lines


def queue_md(report: dict) -> str:
    lines = header_lines(report)
    lines += finding_lines(report["findings"])
    lines += module_lines(report["modules"])
    lines += function_lines(report["functions"])
    return "\n".join(lines) + "\n"


def source_for(path: Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        return None


def parse_tree(source: str) -> ast.Module | None:
    try:
        return ast.parse(source)
    except SyntaxError:
        return None  # broken file — the CRAP audit's test run will flag it


def parsed_pair(source: str) -> tuple[str, ast.Module] | None:
    tree = parse_tree(source)
    if tree is None:
        return None
    return (source, tree)


def parse_source(path: Path) -> tuple[str, ast.Module] | None:
    source = source_for(path)
    if source is None:
        return None
    return parsed_pair(source)


def function_row(fn, rel: str, args_by_line: dict) -> dict:
    return {
        "fullname": fn.fullname, "file": rel, "line": fn.lineno,
        "cyclomatic": fn.complexity, "args": args_by_line.get(fn.lineno, 0),
    }


def rule_value(fn, args_by_line: dict, rule_id: str):
    return fn.complexity if rule_id == "cyclomatic" else args_by_line.get(fn.lineno, 0)


def finding_dict(rule_id: str, rule: dict, value, rel: str, line: int) -> dict:
    return {
        "ruleId": rule_id,
        "severity": rule["severity"],
        "location": {"file": rel, "line": line},
        "message": rule["message"](value),
        "remediation": rule["remediation"],
    }


def append_rule_finding(ctx: dict, rule_id: str, value, rel: str, line: int) -> None:
    rule = RULES[rule_id]
    if rule["check"](value):
        ctx["findings"].append(finding_dict(rule_id, rule, value, rel, line))


def check_rule(ctx: dict, fn, rel: str, args_by_line: dict, rule_id: str) -> None:
    value = rule_value(fn, args_by_line, rule_id)
    append_rule_finding(ctx, rule_id, value, rel, fn.lineno)


def scan_rules(ctx: dict, fn, rel: str, args_by_line: dict) -> None:
    for rule_id in ("cyclomatic", "arguments"):
        check_rule(ctx, fn, rel, args_by_line, rule_id)


def class_methods(fn) -> list:
    return fn.methods


def extend_functions(out: list, methods: list) -> None:
    out += methods


def append_top_function(out: list, fn) -> None:
    if hasattr(fn, "classname"):
        out.append(fn)


def collect_function(out: list, fn) -> None:
    if hasattr(fn, "methods"):
        extend_functions(out, class_methods(fn))
        return
    append_top_function(out, fn)


def file_functions(source: str) -> list:
    """Function entries from cc_visit: expand class methods, skip class objects."""
    out: list = []
    for fn in cc_visit(source):
        collect_function(out, fn)
    return out


def scan_functions(ctx: dict, source: str, rel: str, args_by_line: dict) -> None:
    for fn in file_functions(source):
        ctx["functions"].append(function_row(fn, rel, args_by_line))
        scan_rules(ctx, fn, rel, args_by_line)


def module_mi(source: str) -> float:
    # NB: `multi` is radon's "count docstrings as comments" flag and must
    # be passed positionally — the parameter name is not `multi=`-friendly
    # in older radon versions.
    return mi_compute(*mi_parameters(source, True))


def append_mi_finding(ctx: dict, rel: str, mi: float) -> None:
    append_rule_finding(ctx, "mi", mi, rel, 1)


def scan_module(ctx: dict, source: str, rel: str) -> None:
    mi = module_mi(source)
    ctx["modules"].append({"file": rel, "mi": round(mi, 2), "sloc": len(source.splitlines())})
    append_mi_finding(ctx, rel, mi)


def scan_file(ctx: dict, path: Path) -> None:
    pair = parse_source(path)
    if pair is None:
        return
    source, tree = pair
    rel = path.relative_to(REPO).as_posix()
    ctx["scanned"] += 1
    args_by_line = function_args(tree)
    scan_functions(ctx, source, rel, args_by_line)
    scan_module(ctx, source, rel)


def new_context() -> dict:
    return {"findings": [], "functions": [], "modules": [], "scanned": 0}


def scan_all(ctx: dict) -> None:
    for path in iter_py_files():
        scan_file(ctx, path)


def severity_counts(findings: list[dict]) -> dict[str, int]:
    counts: dict[str, int] = {"high": 0, "moderate": 0}
    for f in findings:
        counts[f["severity"]] = counts.get(f["severity"], 0) + 1
    return counts


def radon_version() -> str:
    return __import__("radon").__version__


def build_report() -> dict:
    ctx = new_context()
    scan_all(ctx)
    by_sev = severity_counts(ctx["findings"])
    return {
        "schemaVersion": 1,
        "target": REPO.name or str(REPO),
        "generator": "radon",
        "generatorVersion": radon_version(),
        "summary": {
            "scannedFiles": ctx["scanned"],
            "functions": len(ctx["functions"]),
            "modules": len(ctx["modules"]),
            "findings": len(ctx["findings"]),
            "bySeverity": by_sev,
            "failing": by_sev["high"] > 0,
        },
        "findings": ctx["findings"],
        "functions": ctx["functions"],
        "modules": ctx["modules"],
    }


def write_reports(report: dict) -> None:
    REPORT.write_text(json.dumps(report, indent=2))
    QUEUE.write_text(queue_md(report))
    s = report["summary"]
    print(f"radon: {s['scannedFiles']} files scanned, {s['functions']} functions, "
          f"{s['findings']} findings ({s['bySeverity']['high']} high), gate = {'FAIL' if s['failing'] else 'pass'}")
    print(f"reports: {REPORT.name}, {QUEUE.name}")


def failing_exit(failing: bool) -> int:
    return 0 if not failing else 1


def gate_exit(report: dict, no_gate: bool) -> int:
    if no_gate:
        return 0
    return failing_exit(report["summary"]["failing"])


def import_radon() -> None:
    global cc_visit, mi_parameters, mi_compute
    try:
        from radon.complexity import cc_visit
        from radon.metrics import mi_parameters, mi_compute
    except ImportError:
        print("error: `radon` not installed", file=sys.stderr)
        print("install: pip install radon", file=sys.stderr)
        raise SystemExit(2)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--no-gate", action="store_true", help="always exit 0")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    import_radon()
    report = build_report()
    write_reports(report)
    return gate_exit(report, args.no_gate)


if __name__ == "__main__":
    sys.exit(main())