#!/usr/bin/env python3
"""Deterministic code-metrics audit for a .NET solution — the verifier half of
the two-agent loop.

Runs `codemetrics` (Dependably.CodeMetrics — the Linux-native, Roslyn-based
successor to the .NET Framework-only Microsoft.CodeAnalysis.Metrics.exe) over
the repo, then:
  - writes metrics-report.json (full codemetrics JSON output)
  - writes metrics-queue.md (worst offenders, worst-first — same shape as
    crap-queue.md so a fix loop can consume it)
  - exit 0 = gate passed; exit 1 = a rule/failOn gate tripped

Gate rules come from `.dependably` in the repo root when the repo declares one
(repo policy: thresholds, excludes, grandfathered exceptions). Without one,
this audit falls back to the skill-bundled default config
(`<script dir>/.dependably.default` — generic thresholds only, no exceptions).

Determinism: given the same source, tool version, and config file the report is
byte-identical. Pin the tool version (see SKILL.md).

Usage: metrics-audit.py [--no-gate]

  --no-gate   run the scan and write reports, but always exit 0 (codemetrics'
              own exit code is otherwise passed through: 1 = a rule/failOn gate
              tripped, 2 = usage error).
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

TOOL = "codemetrics"
DEFAULT_CONFIG_NAME = ".dependably.default"


def git_root(start: Path) -> Path | None:
    try:
        return Path(
            subprocess.check_output(["git", "rev-parse", "--show-toplevel"], cwd=start, text=True, stderr=subprocess.DEVNULL).strip()
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


def git_root_or(first: Path, second: Path) -> Path | None:
    return git_root(first) or git_root(second)


def find_repo() -> Path:
    # Spawned by the quality-loop skill with cwd = current project; also usable
    # standalone from inside the repo. Resolve the repo root from the process
    # cwd first, then from the script dir for legacy/embedded layouts, else
    # fall back to cwd.
    return git_root_or(Path.cwd(), Path(__file__).resolve().parent) or Path.cwd()


REPO = find_repo()
REPORT = REPO / "metrics-report.json"
QUEUE = REPO / "metrics-queue.md"
DEFAULT_CONFIG = Path(__file__).resolve().parent / DEFAULT_CONFIG_NAME


def find_tool(name: str) -> str | None:
    found = shutil.which(name)
    if found:
        return found
    candidate = Path.home() / ".dotnet" / "tools" / name
    return str(candidate) if candidate.exists() else None


def gate_config() -> Path:
    """Repo `.dependably` when the repo declares one, else the bundled default."""
    repo_config = REPO / ".dependably"
    if repo_config.exists():
        return repo_config
    if not DEFAULT_CONFIG.exists():
        raise SystemExit(f"ERROR: bundled default config {DEFAULT_CONFIG} is missing")
    return DEFAULT_CONFIG


def queue_md(data: dict) -> str:
    metrics = data["extra"]["metrics"]
    methods = metrics["Methods"]
    findings = data["findings"]
    s = metrics["Summary"]

    lines = [
        "# Metrics queue (worst offenders, worst-first)",
        "",
        f"Generated by `{TOOL}` (schema v{data['schemaVersion']}) at {data['extra']['Meta']['ToolVersion']}",
        f"Target: `{data['target']}` — {s['Files']} files, {s['Types']} types, {s['Methods']} methods, {s['TotalSloc']} SLOC",
        "",
        f"Summary: avg cyclomatic {s['AverageCyclomatic']}, avg cognitive {s['AverageCognitive']}, "
        f"avg maintainability index {s['AverageMaintainabilityIndex']} (max cc {s['MaxCyclomatic']}, max cognitive {s['MaxCognitive']})",
        "",
        f"Findings: {len(findings)} total "
        f"({data['summary']['bySeverity']['critical']} critical / {data['summary']['bySeverity']['high']} high / "
        f"{data['summary']['bySeverity']['moderate']} moderate / {data['summary']['bySeverity']['low']} low)",
        "",
        "## Findings (worst-first by severity)",
        "",
    ]
    severity_order = {"critical": 0, "high": 1, "moderate": 2, "low": 3}
    for f in sorted(findings, key=lambda f: severity_order.get(f["severity"], 9)):
        loc = f["location"]
        file = loc.get("file") or "(namespace level)"
        line = loc.get("line") or ""
        lines.append(f"- **{f['severity']}** `{f['ruleId']}` [{file}:{line}] {f['message']}")
        lines.append(f"  - Fix: {f['remediation']}")
    lines += ["", "## Lowest maintainability index (methods)", ""]
    for m in sorted(methods, key=lambda m: m["MaintainabilityIndex"])[:15]:
        lines.append(
            f"- MI {m['MaintainabilityIndex']:>5} | cc {m['Cyclomatic']:>2} | sloc {m['Sloc']:>4} | "
            f"{m['Type']}.{m['Name']} ({m['File']}:{m['StartLine']})"
        )
    lines += ["", "## Highest cyclomatic complexity (methods)", ""]
    for m in sorted(methods, key=lambda m: m["Cyclomatic"], reverse=True)[:10]:
        lines.append(
            f"- cc {m['Cyclomatic']:>2} | cognitive {m['Cognitive']:>2} | MI {m['MaintainabilityIndex']:>5} | "
            f"{m['Type']}.{m['Name']} ({m['File']}:{m['StartLine']})"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--no-gate", action="store_true", help="always exit 0")
    args = parser.parse_args()

    tool = find_tool(TOOL)
    if not tool:
        print(f"error: `{TOOL}` not found on PATH or ~/.dotnet/tools", file=sys.stderr)
        print("install: dotnet tool install --global Dependably.CodeMetrics", file=sys.stderr)
        return 2

    # `codemetrics` currently discovers 0 files when given a .sln (it globs C#
    # sources itself); pass the repo root and the gate config explicitly.
    config = gate_config()
    proc = subprocess.run(
        [tool, str(REPO), "--format", "json", "--config", str(config)],
        capture_output=True, text=True, cwd=REPO,
    )
    if proc.returncode not in (0, 1):
        print(proc.stderr, file=sys.stderr)
    try:
        data = json.loads(proc.stdout)
    except json.JSONDecodeError:
        print("error: codemetrics output was not valid JSON", file=sys.stderr)
        print(proc.stderr[-2000:], file=sys.stderr)
        return 2

    REPORT.write_text(proc.stdout)
    QUEUE.write_text(queue_md(data))

    s = data["summary"]
    print(f"codemetrics: {s['scanned']} files scanned, {s['findings']} findings "
          f"(high+ {s['bySeverity']['high'] + s['bySeverity']['critical']}), gate exit = {proc.returncode}")
    print(f"config: {config.name}")
    print(f"reports: {REPORT.name}, {QUEUE.name}")
    return 0 if args.no_gate else proc.returncode


if __name__ == "__main__":
    sys.exit(main())