"""Tests for scripts/python/metrics-audit.py — queue rendering and main().

Covers the markdown queue/report writers (headers, finding bullets, module
and function tables), report wiring, gate exit codes, radon import
handling, and the CLI entry point including the no-gate flag.
"""
from __future__ import annotations

import json
import sys

import pytest

from tests.conftest import METRICS_AUDIT as ma
from tests.test_metrics_audit_findings import mess_source


# ------------------------------------------------------------------ headers

def test_header_lines():
    report = {
        "generatorVersion": "6.0.1",
        "summary": {"scannedFiles": 4, "functions": 10, "modules": 3,
                    "findings": 2, "bySeverity": {"high": 1, "moderate": 1}},
    }
    lines = ma.header_lines(report)
    assert lines[0] == "# Metrics queue (worst offenders, worst-first)"
    assert lines[2] == "Generated by radon 6.0.1 over 4 files — 10 functions in 3 modules"
    assert lines[4] == "Findings: 2 total (1 high / 1 moderate) — high findings fail the gate"
    assert lines[-1] == ""


def test_finding_lines():
    finding = {"severity": "high", "ruleId": "cyclomatic", "location": {"file": "a.py", "line": 3},
               "message": "cc 30 exceeds max 25", "remediation": "extract methods"}
    assert ma.finding_lines([finding]) == [
        "- **high** `cyclomatic` [a.py:3] cc 30 exceeds max 25",
        "  - Fix: extract methods",
    ]


def test_module_lines_sorted_top15():
    modules = [{"mi": 40.0, "sloc": 100, "file": f"m{i}.py"} for i in range(15)]
    modules.append({"mi": 10.0, "sloc": 50, "file": "worst.py"})
    lines = ma.module_lines(modules)
    assert lines[0] == "" and lines[1] == "## Lowest maintainability index (modules)"
    assert len(lines) == 3 + 15
    assert lines[3] == "- MI  10.0 | sloc    50 | worst.py"


def test_module_lines_empty():
    assert ma.module_lines([]) == ["", "## Lowest maintainability index (modules)", ""]


def test_function_lines_sorted_top10():
    functions = [{"cyclomatic": i, "args": 1, "fullname": f"m.f{i}", "file": "m.py", "line": i} for i in range(11)]
    lines = ma.function_lines(functions)
    assert lines[0] == "" and lines[1] == "## Highest cyclomatic complexity (functions)"
    assert len(lines) == 3 + 10
    assert lines[3] == "- cc  10 | args  1 | m.f10 (m.py:10)"


def test_queue_md_assembles_sections():
    report = {
        "generatorVersion": "6.0.1",
        "summary": {"scannedFiles": 1, "functions": 0, "modules": 1, "findings": 0,
                    "bySeverity": {"high": 0, "moderate": 0}},
        "findings": [], "modules": [], "functions": [],
    }
    md = ma.queue_md(report)
    assert md.startswith("# Metrics queue (worst offenders, worst-first)")
    assert "## Findings (worst-first by severity)" in md
    assert "## Lowest maintainability index (modules)" in md
    assert "## Highest cyclomatic complexity (functions)" in md


# -------------------------------------------------------------- report/main

def test_build_report(tmp_path, monkeypatch):
    monkeypatch.setattr(ma, "REPO", tmp_path)
    (tmp_path / "a.py").write_text("def f():\n    return 1\n")
    report = ma.build_report()
    assert report["schemaVersion"] == 1
    assert report["generator"] == "radon"
    assert report["summary"] == {
        "scannedFiles": 1, "functions": 1, "modules": 1, "findings": 0,
        "bySeverity": {"high": 0, "moderate": 0}, "failing": False,
    }


def test_write_reports(tmp_path, monkeypatch, capsys):
    monkeypatch.setattr(ma, "REPORT", tmp_path / "metrics-report.json")
    monkeypatch.setattr(ma, "QUEUE", tmp_path / "metrics-queue.md")
    report = {
        "generatorVersion": "6.0.1",
        "summary": {"scannedFiles": 1, "functions": 0, "modules": 1, "findings": 0,
                    "bySeverity": {"high": 0, "moderate": 0}, "failing": False},
        "findings": [], "functions": [], "modules": [],
    }
    ma.write_reports(report)
    assert (tmp_path / "metrics-report.json").exists()
    assert (tmp_path / "metrics-queue.md").exists()
    assert "radon: 1 files scanned, 0 functions, 0 findings (0 high), gate = pass" in capsys.readouterr().out


def test_failing_exit():
    assert ma.failing_exit(True) == 1
    assert ma.failing_exit(False) == 0


def test_gate_exit():
    report = {"summary": {"failing": True}}
    assert ma.gate_exit(report, no_gate=False) == 1
    assert ma.gate_exit(report, no_gate=True) == 0
    assert ma.gate_exit({"summary": {"failing": False}}, no_gate=False) == 0


def test_import_radon(monkeypatch):
    monkeypatch.setattr(ma, "cc_visit", None)
    monkeypatch.setattr(ma, "mi_parameters", None)
    monkeypatch.setattr(ma, "mi_compute", None)
    ma.import_radon()
    assert callable(ma.cc_visit) and callable(ma.mi_compute) and callable(ma.mi_parameters)


def test_import_radon_missing_raises(monkeypatch, capsys):
    monkeypatch.setitem(sys.modules, "radon.complexity", None)
    with pytest.raises(SystemExit) as e:
        ma.import_radon()
    assert e.value.code == 2
    assert "radon" in capsys.readouterr().err


def test_parse_args(monkeypatch):
    monkeypatch.setattr(sys, "argv", ["metrics-audit.py"])
    assert not ma.parse_args().no_gate
    monkeypatch.setattr(sys, "argv", ["metrics-audit.py", "--no-gate"])
    assert ma.parse_args().no_gate


def test_main_clean_exits_zero(tmp_path, monkeypatch):
    monkeypatch.setattr(ma, "REPO", tmp_path)
    monkeypatch.setattr(ma, "REPORT", tmp_path / "metrics-report.json")
    monkeypatch.setattr(ma, "QUEUE", tmp_path / "metrics-queue.md")
    (tmp_path / "a.py").write_text("def f():\n    return 1\n")
    monkeypatch.setattr(sys, "argv", ["metrics-audit.py"])
    assert ma.main() == 0
    assert (tmp_path / "metrics-report.json").exists()


def test_main_finding_fails_gate(tmp_path, monkeypatch):
    monkeypatch.setattr(ma, "REPO", tmp_path)
    monkeypatch.setattr(ma, "REPORT", tmp_path / "metrics-report.json")
    monkeypatch.setattr(ma, "QUEUE", tmp_path / "metrics-queue.md")
    (tmp_path / "mess.py").write_text(mess_source())
    monkeypatch.setattr(sys, "argv", ["metrics-audit.py"])
    assert ma.main() == 1
    report = json.loads((tmp_path / "metrics-report.json").read_text())
    assert report["summary"]["failing"]
    assert [f["ruleId"] for f in report["findings"]] == ["mi"]


def test_main_no_gate_ignores_findings(tmp_path, monkeypatch):
    monkeypatch.setattr(ma, "REPO", tmp_path)
    monkeypatch.setattr(ma, "REPORT", tmp_path / "metrics-report.json")
    monkeypatch.setattr(ma, "QUEUE", tmp_path / "metrics-queue.md")
    (tmp_path / "mess.py").write_text(mess_source())
    monkeypatch.setattr(sys, "argv", ["metrics-audit.py", "--no-gate"])
    assert ma.main() == 0